version: '3.0'

expectations:
  population_size: 1000

actions:

  # Closed (completed) RTT pathways
  generate_dataset_clockstops:
    run: ehrql:v0 generate-dataset analysis/dataset_definition_clockstops.py 
      --output output/data/dataset_clockstops.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_clockstops.csv.gz  

  measures_any_opioid:
    run: ehrql:v0 generate-measures analysis/measures_any_opioid.py 
      --output output/measures/measures_any_opioid.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_any_opioid.csv
  
  measures_hi_opioid:
    run: ehrql:v0 generate-measures analysis/measures_hi_opioid.py 
      --output output/measures/measures_hi_opioid.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_hi_opioid.csv
        
  # Open (incomplete) RTT pathways
  # generate_dataset_openpathways:
  #   run: ehrql:v0 generate-dataset analysis/dataset_definition_openpathways.py 
  #     --output output/data/dataset_table_openpathways.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/data/dataset_openpathways.csv.gz  
  
  checks_clockstops:
   run: r:latest analysis/clockstops/checks_clockstops.R
   needs: [generate_dataset_clockstops]
   outputs:
      moderately_sensitive:
        data: output/clockstops/*.csv
        plots: output/clockstops/*.png

  opioids_by_week:
   run: r:latest analysis/clockstops/opioids_by_week.R
   needs: [measures_any_opioid, measures_hi_opioid]
   outputs:
      moderately_sensitive:
        data: output/clockstops/opioid*.csv
       # plots: output/clockstops/plot*.png

