version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: ehrql:v0 generate-dataset analysis/dataset_definition.py 
      --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz  