version: '3.0'

expectations:
  population_size: 1000

actions:

  ##### Dataset definitions #####

  # Closed (completed) RTT pathways
  generate_dataset_clockstops:
    run: ehrql:v0 generate-dataset analysis/dataset_definition_clockstops.py 
      --output output/data/dataset_clockstops.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_clockstops.csv.gz  

  # Open (incomplete) RTT pathways
  # generate_dataset_openpathways:
  #   run: ehrql:v0 generate-dataset analysis/dataset_definition_openpathways.py 
  #     --output output/data/dataset_openpathways.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/data/dataset_openpathways.csv.gz  

  ##### Analysis - closed pathways #####
  
  checks_clockstops:
   run: r:latest analysis/clockstops/checks_clockstops.R
   needs: [generate_dataset_clockstops]
   outputs:
      moderately_sensitive:
        data: output/clockstops/*.csv

  final_cohort_clockstops:
   run: r:latest analysis/clockstops/final_cohort_clockstops.R
   needs: [generate_dataset_clockstops]
   outputs:
      highly_sensitive:
        cohort: output/data/cohort*.csv.gz

  full_stats_clockstops:
   run: r:latest analysis/clockstops/full_stats_clockstops.R
   needs: [final_cohort_clockstops]
   outputs:
      moderately_sensitive:
        data1: output/clockstops/rtt_dates.csv
        data2: output/clockstops/cat_var_dist.csv
        data3: output/clockstops/wait_time_pcent.csv
        data4: output/clockstops/wait_time.csv
        data5: output/clockstops/med_counts_by_period.csv
        plots: output/clockstops/plot_*.png

  ortho_stats_clockstops:
   run: r:latest analysis/clockstops/ortho_stats_clockstops.R
   needs: [final_cohort_clockstops]
   outputs:
      moderately_sensitive:
        data1: output/clockstops/rtt_dates_ortho.csv
        data2: output/clockstops/cat_var_dist_ortho.csv
        data3: output/clockstops/wait_time_pcent_ortho.csv
        data4: output/clockstops/wait_time_ortho.csv
        data5: output/clockstops/med_counts_by_period_ortho.csv
        plots: output/clockstops/plot*.png  

  ##### Opioid measures - closed pathways #####
  
  measures_any_opioid:
    run: ehrql:v0 generate-measures analysis/measures_any_opioid.py 
      --output output/measures/measures_any_opioid.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_any_opioid.csv
  
  measures_hi_opioid:
    run: ehrql:v0 generate-measures analysis/measures_hi_opioid.py 
      --output output/measures/measures_hi_opioid.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_hi_opioid.csv
      
  opioids_by_week:
   run: r:latest analysis/clockstops/opioids_by_week.R
   needs: [measures_any_opioid, measures_hi_opioid]
   outputs:
      moderately_sensitive:
        data: output/clockstops/opioid*.csv
        plots: output/clockstops/plo*.png

  ##### Analysis - open pathways #####

  # checks_openpathways:
  #  run: r:latest analysis/openpathways/checks_openpathways.R
  #  needs: [generate_dataset_openpathways]
  #  outputs:
  #     moderately_sensitive:
  #       data: output/openpathways/*.csv

  # final_cohort_openpathways:
  #  run: r:latest analysis/openpathways/final_cohort_openpathways.R
  #  needs: [generate_dataset_openpathways]
  #  outputs:
  #     highly_sensitive:
  #       cohort: output/data/cohor*.csv.gz

  # full_stats_openpathways:
  #  run: r:latest analysis/openpathways/full_stats_openpathways.R
  #  needs: [final_cohort_openpathways]
  #  outputs:
  #     moderately_sensitive:
  #       data1: output/openpathways/rtt_dates_open.csv
  #       data2: output/openpathways/cat_var_dist_open.csv
  #       data3: output/openpathways/wait_time_pcent_open.csv
  #       data4: output/openpathways/wait_time_open.csv
  #       data5: output/openpathways/med_counts_by_period_open.csv
  #       plots: output/openpathways/plot_*.png

  # ortho_stats_openpathways:
  #  run: r:latest analysis/openpathways/ortho_stats_openpathways.R
  #  needs: [final_cohort_openpathways]
  #  outputs:
  #     moderately_sensitive:
  #       data1: output/openpathways/rtt_dates_ortho_open.csv
  #       data2: output/openpathways/cat_var_dist_ortho_open.csv
  #       data3: output/openpathways/wait_time_pcent_ortho_open.csv
  #       data4: output/openpathways/wait_time_ortho_open.csv
  #       data5: output/openpathways/med_counts_by_period_ortho_open.csv
  #       plots: output/openpathways/plot*.png  
