version: '3.0'

expectations:
  population_size: 1000

actions:

  # Closed (completed) RTT pathways
  generate_dataset_clockstops:
    run: ehrql:v0 generate-dataset analysis/dataset_definition_clockstops.py 
      --output output/data/dataset_clockstops.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_clockstops.csv.gz  

  measures_any_opioid:
    run: ehrql:v0 generate-measures analysis/measures_any_opioid.py 
      --output output/measures/measures_any_opioid.csv
      --dummy-data-file dummy/dummy_any_opioid.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_any_opioid.csv
  
  measures_hi_opioid:
    run: ehrql:v0 generate-measures analysis/measures_hi_opioid.py 
      --output output/measures/measures_hi_opioid.csv
      --dummy-data-file dummy/dummy_hi_opioid.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_hi_opioid.csv
        
  # Open (incomplete) RTT pathways
  # generate_dataset_openpathways:
  #   run: ehrql:v0 generate-dataset analysis/dataset_definition_openpathways.py 
  #     --output output/data/dataset_table_openpathways.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/data/dataset_openpathways.csv.gz  
  
  checks_clockstops:
   run: r:latest analysis/clockstops/checks_clockstops.R
   needs: [generate_dataset_clockstops]
   outputs:
      moderately_sensitive:
        data: output/clockstops/*.csv

  full_cohort_clockstops:
   run: r:latest analysis/clockstops/full_cohort_clockstops.R
   needs: [generate_dataset_clockstops]
   outputs:
      highly_sensitive:
        cohort: output/data/cohort_fhttps://github.com/opensafely/waiting-list/pull/7/conflict?name=project.yaml&ancestor_oid=c7e4674b0c9b0b77832ca82a78411dec57a50007&base_oid=578c57ddd0d783d72e11809826a786474d7b74d1&head_oid=035712819bbd4f4eed23372fa74e6f193e9e4d63ull*.csv.gz
      moderately_sensitive:
        data1: output/clockstops/rtt_dates.csv
        data2: output/clockstops/cat_var_dist.csv
        data3: output/clockstops/wait_time_pcent.csv
        data4: output/clockstops/med_counts_by_period.csv
        plots: output/clockstops/plot_*.png

  ortho_clockstops:
   run: r:latest analysis/clockstops/ortho_cohort_clockstops.R
   needs: [full_cohort_clockstops]
   outputs:
      highly_sensitive:
        cohort: output/data/cohort_ortho*.csv.gz
      moderately_sensitive:
        data1: output/clockstops/rtt_dates_ortho.csv
        data2: output/clockstops/cat_var_dist_ortho.csv
        data3: output/clockstops/wait_time_pcent_ortho.csv
        data4: output/clockstops/med_counts_by_period_ortho.csv
        plots: output/clockstops/plot*.png  

  opioids_by_week:
   run: r:latest analysis/clockstops/opioids_by_week.R
   needs: [measures_any_opioid, measures_hi_opioid]
   outputs:
      moderately_sensitive:
        data: output/clockstops/opioid*.csv
        plots: output/clockstops/plo*.png

