version: '3.0'

expectations:
  population_size: 1000

actions:

  # Closed (completed) RTT pathways
  generate_dataset_clockstops:
    run: ehrql:v0 generate-dataset analysis/dataset_definition_clockstops.py 
      --output output/data/dataset_clockstops.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_clockstops.csv.gz  
        
  measures_clockstops:
    run: ehrql:v0 generate-measures analysis/measures_clockstops.py 
      --output output/measures/measures_clockstops.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_clockstops.csv
        
  # Open (incomplete) RTT pathways
  # generate_dataset_openpathways:
  #   run: ehrql:v0 generate-dataset analysis/dataset_definition_openpathways.py 
  #     --output output/data/dataset_openpathways.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/data/dataset_openpathways.csv.gz  
  
  checks_clockstops:
   run: r:latest analysis/clockstops/checks_clockstops.R
   needs: [generate_dataset_clockstops]
   outputs:
      moderately_sensitive:
        data: output/clockstops/*.csv

  full_cohort_clockstops:
   run: r:latest analysis/clockstops/full_cohort_clockstops.R
   needs: [generate_dataset_clockstops]
   outputs:
      highly_sensitive:
        cohort: output/data/cohort_full*.csv.gz
      moderately_sensitive:
        data1: output/clockstops/rtt_dates.csv
        data2: output/clockstops/cat_var_dist.csv
        data3: output/clockstops/wait_time_pcent.csv
        data4: output/clockstops/med_counts_by_period.csv
        plots: output/clockstops/plot_*.png

  ortho_clockstops:
   run: r:latest analysis/clockstops/ortho_clockstops.R
   needs: [full_cohort_clockstops]
   outputs:
      highly_sensitive:
        cohort: output/data/cohort_ortho*.csv.gz
      moderately_sensitive:
        data1: output/clockstops/rtt_date_ortho.csv
        data2: output/clockstops/cat_var_dist_ortho.csv
        data3: output/clockstops/wait_time_pcent_ortho.csv
        data4: output/clockstops/med_counts_by_period_ortho.csv
        plots: output/clockstops/plot*.png  